INSERT INTO WORKOUT (ID, NAME, WEIGHT, BODY_PART, REPS, OWNER) VALUES (2, 'squats', 66, 'LEGS', 8, 'sarah1');
INSERT INTO WORKOUT (ID, NAME, WEIGHT, BODY_PART, REPS, OWNER) VALUES (3, 'Bench Press', 66, 'CHEST', 8, 'sarah1');
INSERT INTO WORKOUT (ID, NAME, WEIGHT, BODY_PART, REPS, OWNER) VALUES (5, 'Shoulder Press', 100, 'LEGS', 8, 'sarah1');
